import React, { useState, useEffect } from 'react';
import { Edit3, Save, X, Trash2, FileText, Plus } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { notesApi } from '../services/api';
import { Note } from '../types';

interface NotesPanelProps {
  sessionId: string | null;
  autoGeneratedNotes: string | null;
  refreshTrigger?: number;
  onNoteCreated?: () => void;
}

const CATEGORIES = ['Key Ideas', 'Decisions', 'Next Steps'] as const;
type CategoryType = typeof CATEGORIES[number];

const NotesPanel: React.FC<NotesPanelProps> = ({ sessionId, autoGeneratedNotes, refreshTrigger, onNoteCreated }) => {
  const [notes, setNotes] = useState<Note[]>([]);
  const [editingNoteId, setEditingNoteId] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [showAddNote, setShowAddNote] = useState<CategoryType | null>(null);
  const [newNoteContent, setNewNoteContent] = useState('');

  useEffect(() => {
    if (sessionId) {
      loadNotes();
    } else {
      setNotes([]);
    }
  }, [sessionId]);

  useEffect(() => {
    // If we have auto-generated notes and no existing notes, they will be loaded via loadNotes
    if (autoGeneratedNotes && sessionId) {
      loadNotes();
    }
  }, [autoGeneratedNotes, sessionId]);

  useEffect(() => {
    if (sessionId && refreshTrigger !== undefined) {
      loadNotes();
    }
  }, [refreshTrigger, sessionId]);

  const loadNotes = async () => {
    if (!sessionId) {
      return;
    }
    
    setIsLoading(true);
    try {
      const notesData = await notesApi.getNotes(sessionId);
      setNotes(notesData);
    } catch (error) {
      console.error('Error loading notes:', error);
      // Don't show alert for loading errors, just log them
    } finally {
      setIsLoading(false);
    }
  };

  const handleEditNote = (note: Note) => {
    setEditingNoteId(note._id);
    setEditContent(note.content);
  };

  const handleSaveNote = async (noteId: string) => {
    if (!editContent.trim()) return;

    try {
      const updatedNote = await notesApi.updateNote(noteId, editContent.trim());
      setNotes(prev => prev.map(note => 
        note._id === noteId ? updatedNote : note
      ));
      setEditingNoteId(null);
      setEditContent('');
    } catch (error) {
      console.error('Error updating note:', error);
      alert('Failed to update note. Please try again.');
    }
  };

  const handleCancelEdit = () => {
    setEditingNoteId(null);
    setEditContent('');
  };

  const handleDeleteNote = async (noteId: string) => {
    if (!window.confirm('Are you sure you want to delete this note?')) return;

    try {
      await notesApi.deleteNote(noteId);
      setNotes(prev => prev.filter(note => note._id !== noteId));
    } catch (error) {
      console.error('Error deleting note:', error);
      alert('Failed to delete note. Please try again.');
    }
  };

  const handleCreateNote = async (category: CategoryType) => {
    if (!newNoteContent.trim() || !sessionId) return;

    try {
      const newNote = await notesApi.createNote(sessionId, newNoteContent.trim(), category);
      setNotes(prev => [...prev, newNote]);
      setNewNoteContent('');
      setShowAddNote(null);
      if (onNoteCreated) {
        onNoteCreated();
      }
    } catch (error) {
      console.error('Error creating note:', error);
      alert('Failed to create note. Please try again.');
    }
  };

  const getCategoryColor = (category: string) => {
    // Use neutral colors for all categories
    return 'bg-gray-100 text-gray-700 border-gray-300';
  };

  const getNotesByCategory = (category: CategoryType) => {
    return notes.filter(note => note.category === category);
  };

  const getEmptyStateMessage = (category: CategoryType) => {
    const messages: { [key in CategoryType]: string } = {
      'Key Ideas': 'Main concepts and insights will appear here',
      'Decisions': 'Choices and directions you agree on',
      'Next Steps': 'Actionable follow-ups and tasks'
    };
    
    return messages[category];
  };

  return (
    <div className="h-full flex flex-col">
      {/* Debug Info (development only) */}
      {/* process.env.NODE_ENV === 'development' && (
        <div className="text-xs bg-yellow-50 border-b border-yellow-200 p-2 text-gray-800">
          <div>SessionId: {sessionId || 'null'}</div>
          <div>Notes count: {notes.length}</div>
          <div>Loading: {isLoading.toString()}</div>
          <div>RefreshTrigger: {refreshTrigger}</div>
          <div>ShowAddNote: {showAddNote.toString()}</div>
        </div>
      ) */}

      {/* Header */}
      <div className="flex-shrink-0 p-3 border-b border-gray-200 bg-white">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0 flex-1">
            <h2 className="text-base font-medium text-gray-900 truncate">Notes</h2>
            <p className="text-xs text-gray-500 mt-1 leading-tight">
              Organized by Key Ideas, Decisions, and Next Steps
            </p>
          </div>
        </div>
      </div>

      {/* Scrollable Notes Content */}
      <div className="flex-1 overflow-y-auto">
        <div className="p-3 space-y-6">
          {/* Loading State */}
          {isLoading && (
            <div className="text-center text-gray-500 py-8">
              <div className="animate-pulse text-xs">Loading notes...</div>
            </div>
          )}

          {/* Notes organized by category */}
          {!isLoading && CATEGORIES.map((category) => {
            const categoryNotes = getNotesByCategory(category);
            const isAdding = showAddNote === category;
            
            return (
              <div key={category} className="space-y-2">
                {/* Category Header */}
                <div className="flex items-center justify-between">
                  <h3 className={`text-base font-medium px-3 py-1.5 rounded-md border ${getCategoryColor(category)}`}>
                    {category}
                  </h3>
                  {!isAdding && sessionId && (
                    <button
                      onClick={() => setShowAddNote(category)}
                      className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 px-2 py-1 rounded hover:bg-gray-100"
                      title={`Add ${category}`}
                    >
                      <Plus size={12} />
                      Add
                    </button>
                  )}
                </div>

                {/* Add Note Form */}
                {isAdding && sessionId && (
                  <div className="bg-gray-50 rounded-lg border border-gray-200 p-3 space-y-2">
                    <textarea
                      value={newNoteContent}
                      onChange={(e) => setNewNoteContent(e.target.value)}
                      placeholder={`Add a ${category.toLowerCase()}...`}
                      className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-500 focus:border-primary-500 resize-none bg-white text-gray-900 placeholder:text-xs placeholder:text-gray-400"
                      rows={3}
                      autoFocus
                    />
                    <div className="flex items-center gap-2 justify-end">
                      <button
                        onClick={() => {
                          setShowAddNote(null);
                          setNewNoteContent('');
                        }}
                        className="px-3 py-1.5 text-xs text-gray-500 hover:text-gray-700 rounded hover:bg-gray-200"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={() => handleCreateNote(category)}
                        disabled={!newNoteContent.trim() || !sessionId}
                        className="px-3 py-1.5 text-sm bg-primary-600 text-white rounded hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                )}

                {/* Notes in this category */}
                {categoryNotes.length === 0 && !isAdding ? (
                  <div className="text-xs text-gray-500 pl-3 py-2">
                    {getEmptyStateMessage(category)}
                  </div>
                ) : (
                  <div className="space-y-2">
                    {categoryNotes.map((note) => (
                      <div key={note._id} className="bg-white rounded-lg border border-gray-200 p-3 shadow-sm">
                        <div className="flex items-start justify-between gap-2 mb-3">
                          <div className="flex items-center gap-2 min-w-0 flex-1">
                            {note.isEdited && (
                              <span className="text-xs px-2 py-1 bg-gray-100 text-gray-500 rounded">
                                Edited
                              </span>
                            )}
                          </div>
                          <div className="flex items-center gap-1 flex-shrink-0">
                            {editingNoteId === note._id ? (
                              <>
                                <button
                                  onClick={() => handleSaveNote(note._id)}
                                  className="p-1.5 text-primary-600 hover:bg-primary-50 rounded"
                                  title="Save"
                                >
                                  <Save size={14} />
                                </button>
                                <button
                                  onClick={handleCancelEdit}
                                  className="p-1.5 text-gray-600 hover:bg-gray-50 rounded"
                                  title="Cancel"
                                >
                                  <X size={14} />
                                </button>
                              </>
                            ) : (
                              <>
                                <button
                                  onClick={() => handleEditNote(note)}
                                  className="p-1.5 text-gray-600 hover:bg-gray-50 rounded"
                                  title="Edit"
                                >
                                  <Edit3 size={14} />
                                </button>
                                <button
                                  onClick={() => handleDeleteNote(note._id)}
                                  className="p-1.5 text-gray-600 hover:bg-gray-50 rounded"
                                  title="Delete"
                                >
                                  <Trash2 size={14} />
                                </button>
                              </>
                            )}
                          </div>
                        </div>

                        {editingNoteId === note._id ? (
                          <textarea
                            value={editContent}
                            onChange={(e) => setEditContent(e.target.value)}
                            className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-500 focus:border-primary-500 resize-none bg-white text-gray-900"
                            rows={6}
                            autoFocus
                          />
                        ) : (
                          <div className="prose prose-sm max-w-none text-sm text-gray-700 leading-relaxed">
                            <ReactMarkdown>{note.content}</ReactMarkdown>
                          </div>
                        )}

                        <div className="mt-3 pt-3 border-t border-gray-100 text-xs text-gray-500">
                          {note.isEdited ? 'Updated' : 'Created'}: {new Date(note.updatedAt).toLocaleString()}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default NotesPanel; 