import React, { useState, useEffect } from 'react';
import { MessageSquare, FileText, Plus } from 'lucide-react';
import ChatInterface from './components/ChatInterface';
import NotesPanel from './components/NotesPanel';
import { Message } from './types';

function AppContent() {
  const [currentSessionId, setCurrentSessionId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [autoGeneratedNotes, setAutoGeneratedNotes] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'chat' | 'notes'>('chat');
  const [refreshTrigger, setRefreshTrigger] = useState(0); // Changed from refreshNotes to refreshTrigger

  const handleSessionCreated = (sessionId: string) => {
    console.log('🆕 App: Session created:', sessionId);
    setCurrentSessionId(sessionId);
  };

  const handleMessagesUpdate = (newMessages: Message[]) => {
    console.log('💬 App: Messages updated, count:', newMessages.length);
    setMessages(newMessages);
  };

  const handleNoteCreated = () => {
    console.log('📝 App: Note created, incrementing refresh trigger from', refreshTrigger, 'to', refreshTrigger + 1);
    // Trigger notes refresh in the NotesPanel
    setRefreshTrigger(prev => prev + 1);
  };

  const handleNotesGenerated = (notes: string) => {
    console.log('🤖 App: Auto-generated notes received, updating state and triggering refresh');
    setAutoGeneratedNotes(notes);
    // Also trigger a refresh to ensure notes panel reloads
    setRefreshTrigger(prev => prev + 1);
  };

  const handleNewSession = () => {
    console.log('🆕 App: Starting new session');
    setCurrentSessionId(null);
    setMessages([]);
    setAutoGeneratedNotes(null);
    setRefreshTrigger(prev => prev + 1);
  };

  return (
    <div className="h-screen bg-gray-50 flex flex-col relative">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 px-6 py-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h1 className="text-base font-semibold text-gray-900">BrainstormAI</h1>
          </div>
          <button
            onClick={handleNewSession}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-700 hover:text-gray-900 bg-gray-50 hover:bg-gray-100 border border-gray-200 rounded-md transition-colors"
            title="Start a new session"
          >
            <Plus size={14} />
            New Session
          </button>
        </div>
        
        {/* Session Info */}
        {currentSessionId && (
          <div className="mt-1.5 text-xs text-gray-500">
            <span>Session: {currentSessionId.slice(0, 8)}...</span>
            <span className="ml-4">{messages.length} messages</span>
          </div>
        )}
      </header>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Desktop Layout */}
        <div className="hidden lg:flex flex-1">
          {/* Chat Section */}
          <div className="flex-1 flex flex-col bg-white border-r border-gray-200">
            <ChatInterface
              sessionId={currentSessionId}
              onSessionCreated={handleSessionCreated}
              messages={messages}
              onMessagesUpdate={handleMessagesUpdate}
              onNotesGenerated={handleNotesGenerated}
            />
          </div>

          {/* Notes Section */}
          <div className="w-96 bg-gray-50/50 border-l-2 border-gray-200">
            <NotesPanel
              sessionId={currentSessionId}
              autoGeneratedNotes={autoGeneratedNotes}
              refreshTrigger={refreshTrigger}
              onNoteCreated={handleNoteCreated}
            />
          </div>
        </div>

        {/* Mobile Layout */}
        <div className="lg:hidden flex-1 flex flex-col">
          {/* Tab Navigation */}
          <div className="bg-white border-b border-gray-200">
            <div className="flex">
              <button
                onClick={() => setActiveTab('chat')}
                className={`flex-1 flex items-center justify-center gap-2 py-3 px-4 text-sm border-b-2 transition-colors ${
                  activeTab === 'chat'
                    ? 'border-primary-600 text-gray-900'
                    : 'border-transparent text-gray-600 hover:text-gray-900'
                }`}
              >
                <MessageSquare size={16} />
                Chat
              </button>
              <button
                onClick={() => setActiveTab('notes')}
                className={`flex-1 flex items-center justify-center gap-2 py-3 px-4 text-sm border-b-2 transition-colors ${
                  activeTab === 'notes'
                    ? 'border-primary-600 text-gray-900'
                    : 'border-transparent text-gray-600 hover:text-gray-900'
                }`}
              >
                <FileText size={16} />
                Notes
              </button>
            </div>
          </div>

          {/* Tab Content */}
          <div className="flex-1 overflow-hidden">
            {activeTab === 'chat' ? (
              <ChatInterface
                sessionId={currentSessionId}
                onSessionCreated={handleSessionCreated}
                messages={messages}
                onMessagesUpdate={handleMessagesUpdate}
                onNotesGenerated={handleNotesGenerated}
              />
            ) : (
              <NotesPanel
                sessionId={currentSessionId}
                autoGeneratedNotes={autoGeneratedNotes}
                refreshTrigger={refreshTrigger}
                onNoteCreated={handleNoteCreated}
              />
            )}
          </div>
        </div>
      </div>

      {/* Footer with Attribution */}
      <footer className="flex-shrink-0 bg-white border-t border-gray-200 px-6 py-2">
        <div className="text-xs text-gray-500 text-center">
          <a 
            href="https://www.flaticon.com/free-icons/idea" 
            title="idea icons"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-gray-700 underline"
          >
            Idea icons created by Good Ware - Flaticon
          </a>
        </div>
      </footer>
    </div>
  );
}

function App() {
  return <AppContent />;
}

export default App;
